#!/usr/bin/env bun
/**
 * Bundle `drizzle/` into a TypeScript module.
 *
 * The Bun runtime reads migrations off the filesystem, but a Cloudflare
 * Worker has none: `drizzle-orm/durable-sqlite/migrator` wants the journal
 * and every statement inlined. This script emits that bundle so the Workers
 * build stays a pure `wrangler deploy` with no extra asset plumbing.
 *
 * Run it after `bun run db:generate` — `bun run db:generate` already chains
 * it. `--check` verifies the committed file is current (used by CI).
 */
/* eslint-disable no-console */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import process from "node:process";
import { fileURLToPath } from "node:url";

const API_DIR = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const DRIZZLE_DIR = join(API_DIR, "drizzle");
const OUT_FILE = join(API_DIR, "src/db/migrations.generated.ts");

interface JournalEntry {
  idx: number;
  when: number;
  tag: string;
  breakpoints: boolean;
}

function build(): string {
  const journal = JSON.parse(readFileSync(join(DRIZZLE_DIR, "meta/_journal.json"), "utf8")) as {
    entries: JournalEntry[];
  };

  const entries = journal.entries.map(e => ({
    idx: e.idx,
    when: e.when,
    tag: e.tag,
    breakpoints: e.breakpoints,
  }));

  const migrations: Record<string, string> = {};
  for (const entry of journal.entries) {
    migrations[`m${String(entry.idx).padStart(4, "0")}`] = readFileSync(
      join(DRIZZLE_DIR, `${entry.tag}.sql`),
      "utf8",
    );
  }

  return `// Generated by scripts/gen-do-migrations.ts — do not edit.
// Source: apps/api/drizzle/. Regenerate with \`bun run db:generate\`.

export default ${JSON.stringify({ journal: { entries }, migrations }, null, 2)} as {
  journal: { entries: { idx: number; when: number; tag: string; breakpoints: boolean }[] };
  migrations: Record<string, string>;
};
`;
}

const next = build();

if (process.argv.includes("--check")) {
  let current = "";
  try {
    current = readFileSync(OUT_FILE, "utf8");
  }
  catch {
    current = "";
  }
  if (current !== next) {
    console.error(`[gen-do-migrations] ${OUT_FILE} is stale. Run \`bun run db:generate\`.`);
    process.exit(1);
  }
  console.log("[gen-do-migrations] up to date");
}
else {
  writeFileSync(OUT_FILE, next);
  console.log(`[gen-do-migrations] wrote ${OUT_FILE}`);
}
